In [9]:
import numpy as np

In [10]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]],np.int8)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(array.shape)

(3, 3)


In [12]:
print (array.dtype)

int8


In [13]:
array[0,1] = 8
print(array)

[[1 8 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(array.shape)

(3, 3)


In [15]:
print(array.size)

9


In [16]:
print(array.ndim)

2


In [18]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
rng = np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
lspace = np.linspace(1,6,12)
print(lspace)

[1.         1.45454545 1.90909091 2.36363636 2.81818182 3.27272727
 3.72727273 4.18181818 4.63636364 5.09090909 5.54545455 6.        ]


In [23]:
emp = np.empty((3,4))
print(emp)

[[1.         1.45454545 1.90909091 2.36363636]
 [2.81818182 3.27272727 3.72727273 4.18181818]
 [4.63636364 5.09090909 5.54545455 6.        ]]


In [25]:
emp_like = np.empty_like(lspace)
print(emp_like)

[1.         1.45454545 1.90909091 2.36363636 2.81818182 3.27272727
 3.72727273 4.18181818 4.63636364 5.09090909 5.54545455 6.        ]


In [27]:
identity = np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
print(identity.shape)

(4, 4)


In [30]:
arr = np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [33]:
arr = arr.reshape(5,20)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [36]:
arr = arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [38]:
print(arr.shape)

(100,)


In [40]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
print(ar.sum(axis = 0))

[12 15 18]


In [45]:
print(ar.sum(axis = 1))

[ 6 15 24]


In [46]:
print(ar.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [48]:
ar.flat

In [49]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [50]:
ar.ndim

2

In [52]:
ar.nbytes

72

In [54]:
one = np.array([1,2,3,5,7,6])
print(one.argmax())
print(one.argmin())

4
0


In [56]:
print(one.argsort())

[0 1 2 3 5 4]


In [57]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
ar.argmax()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.int64(8)

In [59]:
ar.argmin()

np.int64(0)

In [60]:
ar.argmax(axis = 0)

          

array([2, 2, 2])

In [62]:
ar.argmax(axis = 1)

array([2, 2, 2])

In [63]:
ar.argmin(axis = 0)

array([0, 0, 0])

In [64]:
ar.argmin(axis = 1)

array([0, 0, 0])

In [66]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [67]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [70]:
print(ar.ravel())

[1 2 3 4 5 6 7 8 9]


In [71]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [72]:
ar.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [82]:
ar2 = np.array([[1,2,1],[8,6,5],[9,3,5]])
print(ar2.ndim)
ar + ar2

2


array([[ 2,  4,  4],
       [12, 11, 11],
       [16, 11, 14]])

In [74]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [75]:
ar * ar2

array([[ 1,  4,  3],
       [32, 30, 30],
       [63, 24, 45]])

In [76]:
ar.sum()

np.int64(45)

In [77]:
ar.max()

np.int64(9)

In [78]:
ar.min()

np.int64(1)

In [80]:
np.where(ar2>5)

(array([1, 1, 2]), array([0, 1, 0]))

In [83]:
np.count_nonzero(ar2)

np.int64(9)

In [84]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [85]:
ar2[1,2] = 0

In [87]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [88]:
py_ar = [1,2,3,4,5,6]
np_ar = np.array(py_ar)

In [90]:
import sys
sys.getsizeof(1) * len(ar)

84

In [92]:
np_ar.itemsize * np_ar.size

48